version: "3"

tasks:
  deploy:
    dir: ../..
    cmds:
      - gh workflow run web_cd.yaml --ref main

  env-prod:
    dir: .
    cmds:
      - pnpm dlx vercel@59.11.7 env pull .env.prod --environment=production
