// This file is auto-generated by building store-types crate.
// Do not edit this file manually. Instead, edit the Rust types in
// crates/store-types/src/types.rs and run `cargo build -p store-types`.
import { z } from "zod";

import { jsonObject } from "./shared";

export const calendarProviderSchema = z.enum(["apple", "google", "outlook"]);
export type CalendarProvider = z.infer<typeof calendarProviderSchema>;

export const participantSourceSchema = z.enum(["manual", "auto", "excluded"]);
export type ParticipantSource = z.infer<typeof participantSourceSchema>;

export const calendarSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  tracking_id_calendar: z.string(),
  name: z.string(),
  enabled: z.boolean().default(false),
  provider: calendarProviderSchema,
  source: z.preprocess((val) => val ?? undefined, z.string().optional()),
  color: z.preprocess((val) => val ?? undefined, z.string().optional()),
});
export type Calendar = z.infer<typeof calendarSchema>;

export const chatGroupSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  title: z.string(),
});
export type ChatGroup = z.infer<typeof chatGroupSchema>;

export const chatMessageSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  chat_group_id: z.string(),
  role: z.string(),
  content: z.string(),
  metadata: jsonObject(z.any()),
  parts: jsonObject(z.any()),
});
export type ChatMessage = z.infer<typeof chatMessageSchema>;

export const chatShortcutSchema = z.object({
  user_id: z.string(),
  title: z.string(),
  content: z.string(),
});
export type ChatShortcut = z.infer<typeof chatShortcutSchema>;

export const enhancedNoteSchema = z.object({
  user_id: z.string(),
  session_id: z.string(),
  content: z.string(),
  template_id: z.preprocess((val) => val ?? undefined, z.string().optional()),
  position: z.number(),
  title: z.preprocess((val) => val ?? undefined, z.string().optional()),
});
export type EnhancedNote = z.infer<typeof enhancedNoteSchema>;

export const eventSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  tracking_id_event: z.string(),
  calendar_id: z.string(),
  title: z.string(),
  started_at: z.string(),
  ended_at: z.string(),
  location: z.preprocess((val) => val ?? undefined, z.string().optional()),
  meeting_link: z.preprocess((val) => val ?? undefined, z.string().optional()),
  description: z.preprocess((val) => val ?? undefined, z.string().optional()),
  note: z.preprocess((val) => val ?? undefined, z.string().optional()),
  ignored: z.preprocess((val) => val ?? undefined, z.boolean().optional()),
  recurrence_series_id: z.preprocess(
    (val) => val ?? undefined,
    z.string().optional(),
  ),
});
export type Event = z.infer<typeof eventSchema>;

export const generalSchema = z.object({
  user_id: z.string(),
  autostart: z.boolean().default(false),
  telemetry_consent: z.boolean().default(true),
  save_recordings: z.boolean().default(true),
  notification_event: z.boolean().default(true),
  notification_detect: z.boolean().default(true),
  respect_dnd: z.boolean().default(false),
  quit_intercept: z.boolean().default(false),
  ai_language: z.string().default("en"),
  spoken_languages: jsonObject(z.array(z.string())).default(["en"]),
  ignored_platforms: jsonObject(z.array(z.string())).default([]),
  ignored_recurring_series: jsonObject(z.array(z.string())).default([]),
  current_llm_provider: z.preprocess(
    (val) => val ?? undefined,
    z.string().optional(),
  ),
  current_llm_model: z.preprocess(
    (val) => val ?? undefined,
    z.string().optional(),
  ),
  current_stt_provider: z.preprocess(
    (val) => val ?? undefined,
    z.string().optional(),
  ),
  current_stt_model: z.preprocess(
    (val) => val ?? undefined,
    z.string().optional(),
  ),
});
export type General = z.infer<typeof generalSchema>;

export const humanSchema = z.object({
  user_id: z.string(),
  name: z.string(),
  email: z.string(),
  org_id: z.string(),
  job_title: z.preprocess((val) => val ?? undefined, z.string().optional()),
  linkedin_username: z.preprocess(
    (val) => val ?? undefined,
    z.string().optional(),
  ),
  memo: z.preprocess((val) => val ?? undefined, z.string().optional()),
  pinned: z.boolean().default(false),
  pin_order: z.preprocess((val) => val ?? undefined, z.number().optional()),
});
export type Human = z.infer<typeof humanSchema>;

export const mappingSessionParticipantSchema = z.object({
  user_id: z.string(),
  session_id: z.string(),
  human_id: z.string(),
  source: participantSourceSchema.optional(),
});
export type MappingSessionParticipant = z.infer<
  typeof mappingSessionParticipantSchema
>;

export const mappingTagSessionSchema = z.object({
  user_id: z.string(),
  tag_id: z.string(),
  session_id: z.string(),
});
export type MappingTagSession = z.infer<typeof mappingTagSessionSchema>;

export const organizationSchema = z.object({
  user_id: z.string(),
  name: z.string(),
});
export type Organization = z.infer<typeof organizationSchema>;

export const promptSchema = z.object({
  user_id: z.string(),
  task_type: z.string(),
  content: z.string(),
});
export type Prompt = z.infer<typeof promptSchema>;

export const sessionSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  folder_id: z.preprocess((val) => val ?? undefined, z.string().optional()),
  event_id: z.preprocess((val) => val ?? undefined, z.string().optional()),
  title: z.string(),
  raw_md: z.string(),
});
export type Session = z.infer<typeof sessionSchema>;

export const speakerHintSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  transcript_id: z.string(),
  word_id: z.string(),
  type: z.string(),
  value: jsonObject(z.record(z.string(), z.unknown())),
});
export type SpeakerHint = z.infer<typeof speakerHintSchema>;

export const tagSchema = z.object({
  user_id: z.string(),
  name: z.string(),
});
export type Tag = z.infer<typeof tagSchema>;

export const templateSectionSchema = z.object({
  title: z.string(),
  description: z.string(),
});
export type TemplateSection = z.infer<typeof templateSectionSchema>;

export const templateSchema = z.object({
  user_id: z.string(),
  title: z.string(),
  description: z.string(),
  category: z.preprocess((val) => val ?? undefined, z.string().optional()),
  targets: z.preprocess(
    (val) => val ?? undefined,
    jsonObject(z.array(z.string())).optional(),
  ),
  sections: jsonObject(z.array(templateSectionSchema)),
});
export type Template = z.infer<typeof templateSchema>;

export const transcriptSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  session_id: z.string(),
  started_at: z.number(),
  ended_at: z.preprocess((val) => val ?? undefined, z.number().optional()),
  words: z.string().default("[]"),
  speaker_hints: z.string().default("[]"),
});
export type Transcript = z.infer<typeof transcriptSchema>;

export const wordSchema = z.object({
  user_id: z.string(),
  created_at: z.string(),
  transcript_id: z.string(),
  text: z.string(),
  start_ms: z.number(),
  end_ms: z.number(),
  channel: z.number(),
  speaker: z.preprocess((val) => val ?? undefined, z.string().optional()),
  metadata: z.preprocess(
    (val) => val ?? undefined,
    jsonObject(z.record(z.string(), z.unknown())).optional(),
  ),
});
export type Word = z.infer<typeof wordSchema>;

export const providerSpeakerIndexSchema = z.object({
  speaker_index: z.number(),
  provider: z.string().optional(),
  channel: z.number().optional(),
});
export type ProviderSpeakerIndexHint = z.infer<
  typeof providerSpeakerIndexSchema
>;

export const aiProviderSchema = z
  .object({
    type: z.enum(["stt", "llm"]),
    base_url: z.url().min(1),
    api_key: z.string(),
  })
  .refine(
    (data) => !data.base_url.startsWith("https:") || data.api_key.length > 0,
    {
      message: "API key is required for HTTPS URLs",
      path: ["api_key"],
    },
  );
export type AIProvider = z.infer<typeof aiProviderSchema>;
