/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppExtHostRouteImport } from './routes/app/ext-host'
import { Route as AppControlRouteImport } from './routes/app/control'
import { Route as AppPopoutLayoutRouteImport } from './routes/app/popout/_layout'
import { Route as AppOnboardingLayoutRouteImport } from './routes/app/onboarding/_layout'
import { Route as AppMainLayoutRouteImport } from './routes/app/main/_layout'
import { Route as AppPopoutLayoutIndexRouteImport } from './routes/app/popout/_layout.index'
import { Route as AppOnboardingLayoutIndexRouteImport } from './routes/app/onboarding/_layout.index'
import { Route as AppMainLayoutIndexRouteImport } from './routes/app/main/_layout.index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtHostRoute = AppExtHostRouteImport.update({
  id: '/ext-host',
  path: '/ext-host',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPopoutLayoutRoute = AppPopoutLayoutRouteImport.update({
  id: '/popout/_layout',
  path: '/popout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingLayoutRoute = AppOnboardingLayoutRouteImport.update({
  id: '/onboarding/_layout',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMainLayoutRoute = AppMainLayoutRouteImport.update({
  id: '/main/_layout',
  path: '/main',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPopoutLayoutIndexRoute = AppPopoutLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPopoutLayoutRoute,
} as any)
const AppOnboardingLayoutIndexRoute =
  AppOnboardingLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOnboardingLayoutRoute,
  } as any)
const AppMainLayoutIndexRoute = AppMainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/app/control': typeof AppControlRoute
  '/app/ext-host': typeof AppExtHostRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/main': typeof AppMainLayoutRouteWithChildren
  '/app/onboarding': typeof AppOnboardingLayoutRouteWithChildren
  '/app/popout': typeof AppPopoutLayoutRouteWithChildren
  '/app/main/': typeof AppMainLayoutIndexRoute
  '/app/onboarding/': typeof AppOnboardingLayoutIndexRoute
  '/app/popout/': typeof AppPopoutLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/app/control': typeof AppControlRoute
  '/app/ext-host': typeof AppExtHostRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/main': typeof AppMainLayoutIndexRoute
  '/app/onboarding': typeof AppOnboardingLayoutIndexRoute
  '/app/popout': typeof AppPopoutLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/app/control': typeof AppControlRoute
  '/app/ext-host': typeof AppExtHostRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/main/_layout': typeof AppMainLayoutRouteWithChildren
  '/app/onboarding/_layout': typeof AppOnboardingLayoutRouteWithChildren
  '/app/popout/_layout': typeof AppPopoutLayoutRouteWithChildren
  '/app/main/_layout/': typeof AppMainLayoutIndexRoute
  '/app/onboarding/_layout/': typeof AppOnboardingLayoutIndexRoute
  '/app/popout/_layout/': typeof AppPopoutLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/app/control'
    | '/app/ext-host'
    | '/auth/callback'
    | '/app/main'
    | '/app/onboarding'
    | '/app/popout'
    | '/app/main/'
    | '/app/onboarding/'
    | '/app/popout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/app/control'
    | '/app/ext-host'
    | '/auth/callback'
    | '/app/main'
    | '/app/onboarding'
    | '/app/popout'
  id:
    | '__root__'
    | '/app'
    | '/app/control'
    | '/app/ext-host'
    | '/auth/callback'
    | '/app/main/_layout'
    | '/app/onboarding/_layout'
    | '/app/popout/_layout'
    | '/app/main/_layout/'
    | '/app/onboarding/_layout/'
    | '/app/popout/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ext-host': {
      id: '/app/ext-host'
      path: '/ext-host'
      fullPath: '/app/ext-host'
      preLoaderRoute: typeof AppExtHostRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/control': {
      id: '/app/control'
      path: '/control'
      fullPath: '/app/control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/popout/_layout': {
      id: '/app/popout/_layout'
      path: '/popout'
      fullPath: '/app/popout'
      preLoaderRoute: typeof AppPopoutLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding/_layout': {
      id: '/app/onboarding/_layout'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/main/_layout': {
      id: '/app/main/_layout'
      path: '/main'
      fullPath: '/app/main'
      preLoaderRoute: typeof AppMainLayoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/popout/_layout/': {
      id: '/app/popout/_layout/'
      path: '/'
      fullPath: '/app/popout/'
      preLoaderRoute: typeof AppPopoutLayoutIndexRouteImport
      parentRoute: typeof AppPopoutLayoutRoute
    }
    '/app/onboarding/_layout/': {
      id: '/app/onboarding/_layout/'
      path: '/'
      fullPath: '/app/onboarding/'
      preLoaderRoute: typeof AppOnboardingLayoutIndexRouteImport
      parentRoute: typeof AppOnboardingLayoutRoute
    }
    '/app/main/_layout/': {
      id: '/app/main/_layout/'
      path: '/'
      fullPath: '/app/main/'
      preLoaderRoute: typeof AppMainLayoutIndexRouteImport
      parentRoute: typeof AppMainLayoutRoute
    }
  }
}

interface AppMainLayoutRouteChildren {
  AppMainLayoutIndexRoute: typeof AppMainLayoutIndexRoute
}

const AppMainLayoutRouteChildren: AppMainLayoutRouteChildren = {
  AppMainLayoutIndexRoute: AppMainLayoutIndexRoute,
}

const AppMainLayoutRouteWithChildren = AppMainLayoutRoute._addFileChildren(
  AppMainLayoutRouteChildren,
)

interface AppOnboardingLayoutRouteChildren {
  AppOnboardingLayoutIndexRoute: typeof AppOnboardingLayoutIndexRoute
}

const AppOnboardingLayoutRouteChildren: AppOnboardingLayoutRouteChildren = {
  AppOnboardingLayoutIndexRoute: AppOnboardingLayoutIndexRoute,
}

const AppOnboardingLayoutRouteWithChildren =
  AppOnboardingLayoutRoute._addFileChildren(AppOnboardingLayoutRouteChildren)

interface AppPopoutLayoutRouteChildren {
  AppPopoutLayoutIndexRoute: typeof AppPopoutLayoutIndexRoute
}

const AppPopoutLayoutRouteChildren: AppPopoutLayoutRouteChildren = {
  AppPopoutLayoutIndexRoute: AppPopoutLayoutIndexRoute,
}

const AppPopoutLayoutRouteWithChildren = AppPopoutLayoutRoute._addFileChildren(
  AppPopoutLayoutRouteChildren,
)

interface AppRouteRouteChildren {
  AppControlRoute: typeof AppControlRoute
  AppExtHostRoute: typeof AppExtHostRoute
  AppMainLayoutRoute: typeof AppMainLayoutRouteWithChildren
  AppOnboardingLayoutRoute: typeof AppOnboardingLayoutRouteWithChildren
  AppPopoutLayoutRoute: typeof AppPopoutLayoutRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppControlRoute: AppControlRoute,
  AppExtHostRoute: AppExtHostRoute,
  AppMainLayoutRoute: AppMainLayoutRouteWithChildren,
  AppOnboardingLayoutRoute: AppOnboardingLayoutRouteWithChildren,
  AppPopoutLayoutRoute: AppPopoutLayoutRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
