import { readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const watchConfigPath = "apps/watch/apple/Version.xcconfig";

function validateVersion(version) {
  if (
    typeof version !== "string" ||
    version !== version.trim() ||
    !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(version)
  ) {
    throw new Error(
      "The shared release version must use major.minor.patch, for example 1.4.23.",
    );
  }
  return version;
}

function watchConfig(version) {
  return `// Generated by scripts/release-version.mjs from release-version.json.\nMARKETING_VERSION = ${version}\n`;
}

export function readReleaseVersion(root = repositoryRoot) {
  const { version } = JSON.parse(
    readFileSync(join(root, "release-version.json"), "utf8"),
  );
  return validateVersion(version);
}

export function checkReleaseVersion(expected, root = repositoryRoot) {
  const version = readReleaseVersion(root);
  if (expected !== undefined && expected !== version) {
    throw new Error(
      `Requested version ${expected} does not match the shared release version ${version}. Run node scripts/release-version.mjs ${expected} and commit the result first.`,
    );
  }
  if (
    readFileSync(join(root, watchConfigPath), "utf8") !== watchConfig(version)
  ) {
    throw new Error(
      `Watch version is out of sync. Run node scripts/release-version.mjs ${version}.`,
    );
  }
  return version;
}

export function setReleaseVersion(version, root = repositoryRoot) {
  validateVersion(version);
  writeFileSync(
    join(root, "release-version.json"),
    `${JSON.stringify({ version }, null, 2)}\n`,
  );
  writeFileSync(join(root, watchConfigPath), watchConfig(version));
}

if (
  process.argv[1] &&
  realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url))
) {
  try {
    const args = process.argv.slice(2);
    if (args[0] === "--check" && args.length <= 2) {
      checkReleaseVersion(args[1]);
    } else if (args.length === 1) {
      setReleaseVersion(args[0]);
    } else if (args.length === 0) {
      console.log(readReleaseVersion());
    } else {
      throw new Error(
        "Usage: node scripts/release-version.mjs [major.minor.patch | --check [expected-version]]",
      );
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
